url=https://hseclide.clideanalyser.in/
user_ID=manisha.thakare+12@clideanalyser.com
password=Password@123
imagePath=C:\\Users\\lenovo\\Downloads\\Data collection survey module overview.png
description=TBT
employeeAttendence=10
contractorAttendence=10
faculty_Name=AAA
male_Attendence=10
femel_Attendence=10
edit_facuty=AAA1
